/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _PressStart2P_h_
#define _PressStart2P_h_
//---------------------------------------------------------------------------------
extern const unsigned char PressStart2P[];
extern const int PressStart2P_size;
//---------------------------------------------------------------------------------
#endif //_PressStart2P_h_
//---------------------------------------------------------------------------------
